apiVersion: apps/v1
kind: ClusterConfig

metadata:
  name: app
  region: us-west-2

iam:
  withOIDC: true

nodeGroups:
  - name: ng1
    instanceType: t2.medium
    amiFamily: AmazonLinux2
    # desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: KeyPair_Demo
    Tags:
        - Key: Name
          Value: demo  

