apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-devops-app
  namespace: app-devops-app
  labels:
    app: app-devops
spec:
  replicas: 2
  strategy:
    type: RolingUpdate
  selector:
    matchLabels:
      app: app-devops-app
  template:
    metadata:
      labels:
        app: app-devops-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: app-devops-app
          image: mehtaat/app-devops-image:latest
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
