apiVersion: v1
kind: Service
metadata:
  name: app-devops-app
  # namespace:
  # labels:
  #   app: app-devops-app
spec:
  type: LoadBalancer
  selector:
    app: app-devops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
